export interface ProductType {
    id: number | null;
    name: string | null;
    image: string | null;
    unit: string | null;
    base: string | null;
    // All impact (New)
    nrc_manufacturing: number | null;
    nrc_installation: number | null;
    nrc_usage: number | null;
    nrc_end_of_life: number | null;
    nerf_manufacturing: number | null;
    nerf_installation: number | null;
    nerf_usage: number | null;
    nerf_end_of_life: number | null;
    nase_manufacturing: number | null;
    nase_installation: number | null;
    nase_usage: number | null;
    nase_end_of_life: number | null;
    nem_manufacturing: number | null;
    nem_installation: number | null;
    nem_usage: number | null;
    nem_end_of_life: number | null;
    // All impact (reuse)
    rrc_manufacturing: number | null;
    rrc_installation: number | null;
    rrc_usage: number | null;
    rrc_end_of_life: number | null;
    rerf_manufacturing: number | null;
    rerf_installation: number | null;
    rerf_usage: number | null;
    rerf_end_of_life: number | null;
    rase_manufacturing: number | null;
    rase_installation: number | null;
    rase_usage: number | null;
    rase_end_of_life: number | null;
    rem_manufacturing: number | null;
    rem_installation: number | null;
    rem_usage: number | null;
    rem_end_of_life: number | null;
}